import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react'

export type Language = 'ko' | 'en' | 'zh'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// 다국어 텍스트 데이터
const translations = {
  ko: {
    // 헤더
    'header.stayground': 'STAY GROUND.',
    'header.search': '검색',
    'header.login': '로그인',
    'header.signup': '회원가입',
    'header.non_member_reservation': '비회원 예약 조회',
    
    // 홈페이지
    'home.summer_festa_coupon': '썸머 페스타 2만 원 쿠폰 받기',
    'home.only_stayground': 'ONLY STAYGROUND',
    'home.pick': 'PICK',
    'home.earlybird': 'EARLYBIRD',
    'home.check_in_travel': 'CHECK IN TRAVEL',
    'home.promotion': 'PROMOTION',
    'home.magazine': 'MAGAZINE',
    'home.view_all': '전체보기',
    
    // 검색 필터
    'search.destination': '여행지',
    'search.destination_placeholder': '여행지/숙소 검색',
    'search.checkin': '체크인',
    'search.checkin_placeholder': '체크인 날짜 검색',
    'search.checkout': '체크아웃',
    'search.checkout_placeholder': '체크아웃 날짜 검색',
    'search.people': '인원',
    'search.people_placeholder': '인원 선택',
    'search.apply': '적용',
    'search.location': '지역',
    'search.date': '날짜',
    
    // 스테이 페이지
    'stay.title': 'CHECK IN TRAVEL',
    'stay.all_stays': '모든 스테이',
    'stay.ending_soon': '마감 임박 할인',
    'stay.private_stay': '단독 숙소',
    'stay.camping': '캠핑&글램핑',
    'stay.pet_friendly': '반려동물',
    'stay.pool': '수영장',
    'stay.jacuzzi': '자쿠지',
    'stay.hanok': '한옥',
    'stay.ocean_view': '오션뷰',
    'stay.forest_view': '숲뷰',
    'stay.city_view': '시티뷰',
    'stay.harbor_view': '하버뷰',
    'stay.sauna': '사우나',
    'stay.filter': '필터',
    'stay.sort': '추천순',
    'stay.sort_latest': '최신순',
    'stay.sort_popular': '인기순',
    'stay.sort_price_high': '높은 가격순',
    'stay.sort_price_low': '낮은 가격순',
    'stay.search_results': '검색 결과',
    'stay.accommodations': '개의 숙소',
    
    // 공통
    'common.adult': '성인',
    'common.child': '아동',
    'common.infant': '영아',
    'common.person': '명',
    'common.reset': '초기화',
    'common.close': '닫기',
    'common.loading': '로딩 중...',
    'common.inquiry': '문의하기',
    'common.back': '뒤로가기',
    'common.share': '공유',
    'common.copy_link': '링크복사',
    'common.kakao': '카카오톡',
    'common.line': '라인',
    
    // 위치
    'location.all': '전체',
    'location.seoul': '서울',
    'location.busan': '부산',
    'location.daegu': '대구',
    'location.incheon': '인천',
    'location.daejeon': '대전',
    'location.gwangju': '광주',
    'location.ulsan': '울산',
    'location.gyeonggi': '경기도',
    'location.gangwon': '강원도',
    'location.chungnam': '충청남도',
    'location.chungbuk': '충청북도',
    'location.jeonnam': '전라남도',
    'location.jeonbuk': '전라북도 전주시',
    'location.gyeongnam': '경상남도',
    'location.gyeongbuk': '경상북도',
    'location.jeju': '제주도',
    
    // 스테이 페이지 편의시설 번역
    'stay.amenities.four_season_pool': '사계절 온수풀',
    'stay.amenities.bbq': 'BBQ',
    'stay.amenities.outdoor_bath': '노천탕',
    'stay.amenities.fire_pit': '불멍',
    'stay.amenities.walking_trail': '산책로',
    'stay.amenities.terrace': '테라스',
    'stay.amenities.breakfast': '조식',
    'stay.amenities.smart_home': '스마트홈',
    'stay.amenities.fitness': '피트니스(헬스장)',
    'stay.amenities.yoga': '요가',
    'stay.amenities.karaoke': '노래방',
    
    // 네비게이션
    'nav.stay': '스테이',
    'nav.promotion': '프로모션',
    'nav.earlybird': '얼리버드',
    'nav.magazine': '매거진',
    'nav.about': 'by. STAYBILITY',
    
    // 숙소 상세 페이지
    'accommodation.room_type': '객실타입',
    'accommodation.standard_capacity': '기준 2인 (최대 6인)',
    'accommodation.room_details': '침실(2) 화장실(3) 거실(1) 주방(1)',
    'accommodation.checkin_time': '체크인 15:00 - 체크아웃 11:00',
    'accommodation.per_night': '/ 1박',
    'accommodation.book_now': '예약하기',
    'accommodation.points': '포인트',
    'accommodation.room_info': '객실별 안내 사항',
    'accommodation.amenities': '전 객실 포함 사항',
    'accommodation.view_all_amenities': '전체보기',
    'accommodation.notice': '안내사항을 확인하세요',
    'accommodation.location_info': '위치안내',
    'accommodation.rules': '이용규칙',
    'accommodation.refund_policy': '환불정책',
    'accommodation.safety': '안전시설',
    'accommodation.pricing': '요금정책',
    'accommodation.contact_info': '연락처',
    'accommodation.address': '주소',
    'accommodation.phone': '전화번호',
    'accommodation.email': '이메일',
    'accommodation.basic_rate': '기본 요금',
    'accommodation.peak_rate': '성수기 요금',
    'accommodation.experience': '체험',
    
    // 프로모션 페이지
    'promotion.events': '이벤트',
    'promotion.promotions': '프로모션',
    
    // 얼리버드 페이지
    'earlybird.title': 'EARLYBIRD',
    
    // 매거진 페이지
    'magazine.title': 'MAGAZINE',
    
    // 푸터
    'footer.company': '회사',
    'footer.about': '회사소개',
    'footer.team': '팀',
    'footer.careers': '채용',
    'footer.press': '보도자료',
    'footer.support': '고객지원',
    'footer.help': '도움말',
    'footer.contact': '문의하기',
    'footer.terms': '이용약관',
    'footer.privacy': '개인정보처리방침',
    'footer.cookies': '쿠키 정책',
    'footer.social': '소셜',
    'footer.facebook': '페이스북',
    'footer.instagram': '인스타그램',
    'footer.twitter': '트위터',
    'footer.youtube': '유튜브',
    
    // 숙소 카드
    'accommodation.max_capacity': '최대',
    'accommodation.people': '인',
    'accommodation.location_separator': ' | ',
    
    // 숙소 상세 페이지 추가
    'accommodation.room_name': '뭇별',
    'accommodation.room_description': '바다와 대나무, 별의 울림이 깃든 공간',
    'accommodation.room_description_detail1': '이곳은 바다를 향해 열린 프라이빗한 공간으로, 노출 콘크리트와 유리, 대나무를 활용하여 자연의 요소를 건축 안으로 들였다. 마당의 수공간과 실내외를 잇는 통유리창은 외부의 풍경을 내부로 끌어들이며, 어느 곳에서든 자연을 감상할 수 있게 한다.',
    'accommodation.room_description_detail2': '객실 내부는 미니멀한 디자인으로 꾸며져 있으며, 필요한 모든 편의시설을 갖추고 있어 편안한 휴식을 제공한다. 공간에 들어서면 가장 먼저 대나무가 바람에 스치는 소리가 방문객을 맞이한다. 이는 자연이 연주하는 음악처럼, 마음의 평온을 가져다준다.',
    'accommodation.room_description_detail3': '내부의 욕조에 몸을 담그고 창밖의 대나무 숲을 바라보며 온전한 쉼을 경험할 수 있다. 프라이빗한 마당에는 사계절 내내 즐길 수 있는 온수풀이 마련되어 있다. 따뜻한 물에 몸을 담그고, 변화하는 자연의 풍경을 감상하며 여유로운 시간을 보낼 수 있다.',
    'accommodation.booking_checkin': '체크인',
    'accommodation.booking_checkout': '체크아웃',
    'accommodation.booking_people': '인원',
    'accommodation.booking_adult': '성인',
    'accommodation.booking_people_count': '명',
    'accommodation.hero_title_en': 'Rest in a cluster of stars',
    'accommodation.hero_title_kr': '별의 군락 속에서 맞이하는 안식',
    
    // 푸터 회사 정보
    'footer.company_name': '스테이그라운드',
    'footer.ceo': '대표이사',
    'footer.ceo_name': '정민혁',
    'footer.phone': '대표전화',
    'footer.phone_number': '1588-6198',
    'footer.email': 'stayground@staybility.co.kr',
    'footer.address': '주소',
    'footer.address_detail': '대구광역시 북구 호암로 51, 4층',
    'footer.business_number': '사업자등록번호',
    'footer.business_number_detail': '808-85-02772',
    'footer.commerce_number': '통신판매업등록번호',
    'footer.commerce_number_detail': '제 2024-대구북구-0886 호',
    'footer.tourism_number': '관광사업자등록번호',
    'footer.tourism_number_detail': '제 2023-000005호',
    'footer.disclaimer': '스테이그라운드는 통신판매 중개자로서 통신판매의 당사자가 아니며 상품의 예약, 이용 및 환불 등과 관련한 의무와 책임은 각 판매자에게 있습니다.',
    'footer.copyright': 'Copyright © 2023 STAYBILITY All Rights Reserved.',
    
    // 숙소 더미 데이터
    'accommodation.names.neulimihak': '느린미학',
    'accommodation.names.dallyard': '달리야드',
    'accommodation.names.nuun_seop': '누운 섶',
    'accommodation.names.forest_house': '숲속의 집',
    'accommodation.names.ocean_view_pension': '바다뷰 펜션',
    'accommodation.names.mountain_villa': '산중턱 별장',
    'accommodation.names.city_oasis': '도시의 오아시스',
    'accommodation.names.rural_life': '전원생활',
    'accommodation.names.healing_stay': '힐링 스테이',
    'accommodation.names.sensational_stay': '감성숙소',
    'accommodation.names.peaceful_rest': '평화로운 휴식',
    'accommodation.names.nature_stay': '자연 속 숙소',
    'accommodation.names.healing_pension': '힐링 펜션',
    'accommodation.names.mountain_resort': '산악 휴양지',
    'accommodation.names.ocean_near_stay': '바다 근처 숙소',
    'accommodation.names.grid_jeju': '그리드 제주',
    'accommodation.names.jogak_night': '조각밤',
    
    // 숙소 설명
    'accommodation.descriptions.neulimihak': '느린미학은 경주의 역사와 문화를 담은 아름다운 숙소입니다. 전통과 현대가 조화를 이루는 공간에서 특별한 휴식을 경험하실 수 있습니다.',
    'accommodation.descriptions.dallyard': '달리야드는 제주의 아름다운 자연 속에서 현대적인 편안함을 제공하는 특별한 숙소입니다.',
    'accommodation.descriptions.nuun_seop': '누운 섶은 제주의 전통과 현대가 조화를 이루는 아름다운 숙소입니다.',
    
    // 위치 더미 데이터
    'location.gyeongju': '경상북도 경주시',
    'location.jeju_seogwipo': '제주도 서귀포시',
    'location.jeju_city': '제주도 제주시',
    'location.gapyeong': '경기도 가평군',
    'location.pyeongchang': '강원도 평창군',
    'location.taean': '충청남도 태안군',
    'location.yeosu': '전라남도 여수시',
    'location.geoje': '경상남도 거제시',
    'location.gangneung': '강원도 강릉시',
    'location.danyang': '충청북도 단양군',
    'location.andong': '경상북도 안동시',
    'location.chuncheon': '강원도 춘천시',
    'location.gongju': '충청남도 공주시',
    'location.suncheon': '전라남도 순천시',
    'location.tongyeong': '경상남도 통영시',
    'location.sokcho': '강원도 속초시',
    
    // 프로모션 데이터
    'promotion.bosque_summer': '보스케 썸머 프로모션',
    'promotion.bosque_summer_desc': '여름 특별 할인 프로모션',
    'promotion.bosque_summer_cta': '지금 예약하기',
    'promotion.jogak_night': '조각밤 9월 프로모션',
    'promotion.jogak_night_desc': '9월 한정 특별 프로모션',
    'promotion.jogak_night_cta': '예약하기',
    'promotion.summer_festa': '스테이그라운드 썸머 페스타',
    'promotion.summer_festa_desc': '여름 축제 특별 이벤트',
    'promotion.summer_festa_cta': '쿠폰 받기',
    'promotion.summer_festa_detail': '여름 휴가를 준비하는 여러분에게 스테이그라운드에서 특별한 혜택을 선물합니다. 2만원 할인쿠폰으로 더욱 특별한 여름 휴가를 즐겨보세요!',
    'promotion.family_month': '가정의 달 여행지원금',
    'promotion.family_month_desc': '2만원 쿠폰 받기',
    'promotion.family_month_detail': '가정의 달 5월을 맞아, 스테이그라운드에 입점한 모든 공간 예약 시 적용할 수 있는 2만원 할인쿠폰을 선물 드립니다. 사랑하는 이들과 누리는 특별한 휴식, 스테이그라운드의 선물과 함께해 보세요!',
    'promotion.kb_pay': 'KB Pay가 선물드려요! [5회차]',
    'promotion.kb_pay_desc': '여행하기 좋은 날씨, 감성숙소 어디 갈지 고민 중이신가요? KB Pay에서 무료로 제공합니다.',
    'promotion.kb_pay_detail': '여행하기 좋은 날씨, 감성숙소 어디 갈지 고민 중이신가요? KB Pay에서 무료로 제공합니다. KB Pay 결제 시 추가 혜택을 받아보세요!',
    'common.view_more': '더보기',
    
    // PICK 섹션 데이터
    'pick.title_1': '둥글게 자리 잡은 평온함',
    'pick.subtitle_1': '온원',
    'pick.title_2': '둥글게 자리 잡은 평온함',
    'pick.subtitle_2': '온원',
    'pick.title_3': '둥글게 자리 잡은 평온함',
    'pick.subtitle_3': '온원',
    'pick.title_4': '둥글게 자리 잡은 평온함',
    'pick.subtitle_4': '온원',
    'pick.title_5': '둥글게 자리 잡은 평온함',
    'pick.subtitle_5': '온원',
    'pick.title_6': '둥글게 자리 잡은 평온함',
    'pick.subtitle_6': '온원',
    'pick.title_7': '둥글게 자리 잡은 평온함',
    'pick.subtitle_7': '온원',
    'pick.title_8': '둥글게 자리 잡은 평온함',
    'pick.subtitle_8': '온원',
    'pick.title_9': '둥글게 자리 잡은 평온함',
    'pick.subtitle_9': '온원',
    'pick.title_10': '둥글게 자리 잡은 평온함',
    'pick.subtitle_10': '온원',
    
    // 얼리버드 데이터
    'earlybird.title_text': '얼리버드 특가',
    'earlybird.description': '한정 수량 특별 할인',
    'earlybird.cta': '지금 예약하기',
    
    // 매거진 데이터
    'magazine.seowajeong': '서와정',
    'magazine.seowajeong_desc': '전통과 현대가 만나는 공간',
    'magazine.magazine_1': '매거진 1호',
    'magazine.magazine_2': '매거진 2호',
    'magazine.magazine_3': '매거진 3호',
    'magazine.magazine_4': '매거진 4호',
    'magazine.title_46': '바쁜 일상에서 벗어나 즐기는 찰나의 휴식',
    'magazine.title_45': '바다와 함께하는 특별한 휴식, 해변가의 평온',
    'magazine.title_44': '숲속에서 만나는 평온, 자연과 함께하는 휴식',
    'magazine.title_43': '나를 위한 시간, 비우담',
    'magazine.title_42': '자연 속에서 찾는 내면의 평화',
    'magazine.title_41': '도시를 벗어나 만나는 새로운 경험',
    'magazine.title_40': '시간을 잊고 즐기는 완벽한 휴식',
    'magazine.title_39': '소소한 일상의 아름다움을 발견하는 순간',
    'magazine.title_38': '바람과 함께하는 자유로운 여행',
    'magazine.title_37': '별빛 아래에서의 로맨틱한 밤',
    'magazine.title_36': '산과 바다가 만나는 곳에서의 힐링',
    'magazine.title_35': '전통과 현대가 조화를 이루는 공간',
    'magazine.title_34': '계절의 변화를 느끼는 특별한 공간',
    'magazine.title_33': '마음의 여유를 찾는 힐링 타임',
    'magazine.title_32': '자연과 함께하는 생태 여행',
    'magazine.title_31': '도시를 벗어나 만나는 새로운 경험',
    
    // 매거진 페이지
    'magazine.page_title': '매거진',
    
    // 숙소 상세 페이지
    'accommodation.room_info.standard_capacity': '기준 인원',
    'accommodation.room_info.checkin': '체크인',
    'accommodation.room_info.checkout': '체크아웃',
    'accommodation.room_info.area': '객실 면적',
    'accommodation.room_info.spaces': '객실 공간',
    'accommodation.room_info.bed_types': '침대 유형',
    'accommodation.room_info.title': '객실별 안내 사항',
    'accommodation.room_info.people': '명',
    'accommodation.room_info.max_people': '최대',
    'accommodation.amenities.title': '전 객실 포함 사항',
    'accommodation.amenities.view_all': '전체보기',
    'accommodation.amenities.hair_dryer': '드라이어',
    'accommodation.amenities.coffee_machine': '커피머신',
    'accommodation.amenities.bathroom_amenities': '욕실 어메니티',
    'accommodation.amenities.condiments': '조미료',
    'accommodation.amenities.outdoor_slippers': '외부용 슬리퍼',
    'accommodation.amenities.microwave': '전자레인지',
    'accommodation.amenities.hand_sanitizer': '손 세정제',
    'accommodation.amenities.coffee_pot': '커피포트',
    'accommodation.amenities.refrigerator': '냉장고',
    'accommodation.amenities.air_conditioner': '에어컨',
    'accommodation.amenities.tv': 'TV',
    'accommodation.amenities.induction': '인덕션',
    'accommodation.amenities.cooking_utensils': '조리도구',
    'accommodation.amenities.tableware': '식기',
    'accommodation.amenities.wine_opener': '와인 오프너',
    'accommodation.amenities.wine_glass': '와인잔',
    'accommodation.amenities.towel': '타올',
    'accommodation.amenities.diffuser': '디퓨저',
    'accommodation.info.title': '안내사항을 확인하세요',
    'accommodation.info.location': '위치안내',
    'accommodation.info.rules': '이용규칙',
    'accommodation.info.refund': '환불정책',
    'accommodation.info.safety': '안전시설',
    'accommodation.info.pricing': '요금정책',
    'accommodation.info.address': '주소',
    'accommodation.info.contact': '연락처',
    'accommodation.info.email': '이메일',
    'accommodation.pricing.off_peak': '준성수기',
    'accommodation.pricing.peak': '성수기',
    'accommodation.pricing.high_peak': '극성수기',
    'accommodation.pricing.weekday': '평일',
    'accommodation.pricing.weekend': '주말',
    'accommodation.pricing.category': '구분',
    'accommodation.pricing.note': '자세한 요금은 일정 선택 후 확인하시길 바랍니다.',
    'accommodation.inquiry': '문의하기',
    
    // 숙소 상세 페이지 탭 내용
    'accommodation.tab.room_spaces': '침실(1), 화장실(2), 거실(1), 주방(1)',
    'accommodation.tab.checkin_checkout': '입실과 퇴실',
    'accommodation.tab.checkin_time': '체크인은 오후 3시, 체크아웃은 오전 11시입니다.',
    'accommodation.tab.standard_capacity_detail': '기준인원 2인, 최대 6인(영유아포함)이며 성인 및 아동은 5인까지입니다. 최대 인원 초과시 절대 입실이 불가합니다',
    'accommodation.tab.child_age': '아동 적용 나이는 12세까지 입니다',
    'accommodation.tab.visitor_policy': '게스트 외 방문객은 기준인원 내 추가요금 부과 후 이용가능합니다(인원 초과시 불가)',
    'accommodation.tab.pet_policy': '반려동물을 사랑하지만 여러사람이 사용하는 공간이기에 동반 입실은 불가합니다',
    'accommodation.tab.cleaning_service': '연박시 청소서비스는 제공되지 않습니다.',
    
    // 이용규칙 탭 내용
    'accommodation.tab.room': '객실',
    'accommodation.tab.room_kids_warning': 'Yes-kids zone이나 어린이를 배려해서 설계된 공간이 아니므로 보호자님의 각별한 주의가 필요하며 부주의에 의한 사고시에 책임지지 않습니다. (자쿠지, 수영장, 계단 등의 공간은 특히 조심 해 주세요.)',
    'accommodation.tab.room_cooking_ban': '객실 내에서 고기, 생선, 튀김 등 냄새가 많이나거나 기름기가 많은 음식조리를 엄격히 금지합니다.',
    'accommodation.tab.room_damage_policy': '입실 전 비품관리를 세게히 하고있습니다. 파손된 부분 등은 미리 말씀드리고있으니 체크 부탁드리며 입실 후 발생되는 심한오염, 튜브파손, 염색으로인한 오염, 등 회복어려운 훼손은 부득이 동일제품 구매가격을 청구나 수리비용이 청구되니 주의해 주시면 감사하겠습니다. (오염사례가 빈번한 염색, 아이들 슬라임 놀이등은 금해주시기 바랍니다.)',
    'accommodation.tab.room_wood_care': '식탁 및 싱크대가 나무로 되어 있기에 화기에 취약합니다. 조리시 가열된 냄비를 바로 올려놓지 않도록 주의 해주세요.',
    'accommodation.tab.room_slippers': '실내슬리퍼는 실내에서만, 외부슬리퍼는 정원내에서만 사용 부탁드립니다.',
    
    'accommodation.tab.outdoor_safety': '야외활동 및 안전',
    'accommodation.tab.outdoor_fire_ban': '화재의 위험성으로 가든내에서의 흠연, 촛불 및 불꽃놀이, 개인화로, 부탄가스 등은 절대 사용금지입니다.',
    
    'accommodation.tab.jacuzzi_guide': '자쿠지안내',
    'accommodation.tab.jacuzzi_notice': '자쿠지에 비치된 안내사항을 참고 부탁드립니다.',
    'accommodation.tab.jacuzzi_bath_salt': '준비된 입욕제 외 사용시 욕조가 물들 수 있어 모든 개인입욕제 사용을 금지하며 개인입욕제 사용 후 물듬경우 부득이 청소요금이 부과되오니 주의 부탁드립니다.',
    'accommodation.tab.jacuzzi_water_overflow': '욕조물이 넘치지 않도록 주의 바랍니다. (물 받는 시간 40분 소요)',
    'accommodation.tab.jacuzzi_surface': '자쿠지 내부 논슬립 시공 후 최대한 안전하게 조치를 하였으나(둥글게 갈아냄) 거칠게 느껴질 수 있으니 가벼운 옷, 수영복 착용 후 이용하시기 바랍니다.',
    'accommodation.tab.jacuzzi_children': '유아.어린이 사용시 꼭 보호자 동반하에 이용 바랍니다.',
    'accommodation.tab.jacuzzi_drain': '사용 후 받은 물은 완전히 배수 부탁드립니다.',
    'accommodation.tab.jacuzzi_plug': '자쿠지 마개는 손잡이 부분이 위쪽으로 향하도록 닫아주시고 혹시 뒤집어 닫으셨을 경우에는 당황하지 마시고 연락 부탁드립니다.',
    
    'accommodation.tab.barbecue_guide': '바베큐 안내',
    'accommodation.tab.barbecue_equipment': '바베큐를 옵션에서 추가하신 경우 전기그릴이 준비됩니다.',
    'accommodation.tab.barbecue_weather': '눈.비. 강풍시 이용이 무조건 불가합니다',
    'accommodation.tab.barbecue_shopping': '입실당일 날씨확인 후 고기류 장보기 해주세요',
    'accommodation.tab.barbecue_cleanup': '바베큐 그릴 사용 후 키친타올로 가볍게 닦아주시고 꼭 코드를 뽑아주세요(화재위험)',
    
    'accommodation.tab.pool_guide': '수영장안내',
    'accommodation.tab.pool_temperature': '수영장은 32-33도 미온수로 유지됩니다.',
    'accommodation.tab.pool_weather_effect': '야외수영장 특성상 수온은 날씨와 온도 영향을 많이 받으므로 체감온도는 다를 수 있습니다.',
    'accommodation.tab.pool_depth': '수영장 내부가 점차적으로 깊어지는 형태로 논슬립 시공 되어있으나 뛰어 들어가는 행위는 안전사고를 유발하니 각별히 주의 부탁 드립니다.',
    'accommodation.tab.pool_diaper': '영유아는 방수 기저귀 착용 후 이용 부탁드립니다.',
    'accommodation.tab.pool_debris': '외부수영장 특성상 낙엽. 곤충 등의 이물질이 유입될 수 있음을 알려드리며 구비된 뜰채를 사용하여 제거 후 사용 부탁드립니다.',
    'accommodation.tab.pool_water_quality': '수질은 여과장치를 통해 관리되고 있으며 주기적인 청소를 진행하니 안심하고 사용 해 주세요.',
    'accommodation.tab.pool_contamination': '수영장에 입욕제 및 이물질(배뇨, 입욕제, 꽃잎, 거품, 모래)의 투입을 절대 삼가하여 주시기 바랍니다.',
    'accommodation.tab.pool_depth_range': '수영장 수심은 0.2m~1.2m로 보호자의 동반 입수시에만 어린이의 이용이 가능하도록 협조 부탁드리며 안전사고에 유의 바랍니다.',
    'accommodation.tab.pool_weather_limit': '폭설, 태풍 등 기상악화에 따른 이용제한이 있을 수 있습니다. 게스트분들의 안전을 위한 조치이니 양해 부탁드립니다.',
    'accommodation.tab.pool_hours': '수영장 이용시간 제한은 없으나 미온수는 4시~9시까지 유지됩니다.',
    
    'accommodation.tab.ethanol_fire': '에탄올불멍',
    'accommodation.tab.ethanol_reservation': '에탄올 불멍은 사전예약의 경우 사용하실 수 있도록 준비해 드립니다.',
    'accommodation.tab.ethanol_usage': '준비된 에탄올을 골고루 투입구에 주입 후 불을 붙이면 수분 내로 타오릅니다.',
    'accommodation.tab.ethanol_danger': '사용 중 에탄올을 추가 투입하는 행위는 매우 위험하니 도중에 에탄올을 투입라는 행위는 삼가주시기 바랍니다.',
    'accommodation.tab.ethanol_weather': '기상상황에 따라 제한될 수 있습니다. 비오는날은 이용 불가합니다',
    
    'accommodation.tab.supplies': '본채/별채 구비물품',
    'accommodation.tab.main_building': '본채',
    'accommodation.tab.seasoning': '조미료(간장 오일 설탕 소금)',
    'accommodation.tab.kitchen_appliances': '토스터기, 전기포트, 캡슐커피머신, 인덕션, 정수기, 전자레인지',
    'accommodation.tab.entertainment': '디터람스브라운 스피커, 스탠바이미(넷플릭스)',
    'accommodation.tab.slippers': '실내화 및 외부슬리퍼(흰색)',
    'accommodation.tab.laundry': '빨래건조대, 튜브공기주입기',
    'accommodation.tab.tubes': '성인용 튜브1, 아동용튜브1(요청시)',
    'accommodation.tab.beach_towel': '비치타올',
    'accommodation.tab.insect_repellent': '모기기피제, 모기향, 벌레퇴치제, 물파스',
    'accommodation.tab.chargers': '충전기 (c타입, 5핀, 아이폰)',
    'accommodation.tab.baby_chair': '아기의자(요청시 제공)',
    'accommodation.tab.grill_table': '전기그릴 / 야외접이식 테이블(요청시)',
    'accommodation.tab.bathroom_supplies': '칫솔, 치약, 욕실어메니티, 입욕제',
    'accommodation.tab.bathrobe': '샤워가운은 입실전 요청시에만 제공됩니다',
    
    'accommodation.tab.guest_house': '별채',
    'accommodation.tab.marshall_speaker': '마샬스피커',
    
    'accommodation.tab.supplies_note': '*구비 물품 외 아기식기 및 유아용품, 폼클렌징, 화장품은 준비 해 주세요.',
    'accommodation.tab.damage_note': '*모든 비품은 입실전 정상작동 체크하며 퇴실시 파손발견된 경우 배상요구됩니다',
    
    // 환불정책 탭 내용
    'accommodation.tab.refund_date': '기준일',
    'accommodation.tab.refund_amount': '환불 금액',
    'accommodation.tab.refund_20_days': '체크인 20일 전까지',
    'accommodation.tab.refund_14_days': '체크인 14일 전까지',
    'accommodation.tab.refund_8_days': '체크인 8일 전까지',
    'accommodation.tab.refund_7_days': '체크인 7일 전까지',
    'accommodation.tab.refund_6_days': '체크인 6일 전까지',
    'accommodation.tab.refund_5_days': '체크인 5일 전까지',
    'accommodation.tab.refund_4_days': '체크인 4일 전까지',
    'accommodation.tab.refund_3_days': '체크인 3일 전부터',
    'accommodation.tab.refund_100': '100% 환불',
    'accommodation.tab.refund_90': '90% 환불',
    'accommodation.tab.refund_80': '80% 환불',
    'accommodation.tab.refund_70': '70% 환불',
    'accommodation.tab.refund_60': '60% 환불',
    'accommodation.tab.refund_50': '50% 환불',
    'accommodation.tab.refund_40': '40% 환불',
    'accommodation.tab.refund_no': '환불 불가',
    'accommodation.tab.refund_note': '환불 수수료는 예약 완료 후 24시간 이내 취소와 관련없이 무조건 환불규정을 따름',
    
    // 안전시설 탭 내용
    'accommodation.tab.fire_extinguisher': '소화기',
    'accommodation.tab.fire_main_building': '본채-객실 내 1층 화장실',
    'accommodation.tab.fire_guest_house': '별채-세면대 아래 수납함',
    'accommodation.tab.first_aid': '상비약',
    'accommodation.tab.first_aid_items': '물파스, 모기기피제, 대일밴드, 소독약',
    
    // 요금정책 탭 내용
    'accommodation.pricing.basic_rate': '기본 요금',
    'accommodation.pricing.peak_season_rate': '성수기 요금',
    'common.currency_unit': '원',
    
    // Experience 섹션
    'experience.yeoju.title': '여주현 : 동천',
    'experience.yeoju.subtitle': '아름다운 산세 속 하룻밤의 신선놀음',
    'experience.layr.title': 'LAYR',
    'experience.layr.subtitle': '레이어 한옥 하우스',
    'experience.layr.description': '내면의 취향을 일깨우는 공간',
    'experience.timezone.title': '고유시차',
    'experience.timezone.subtitle': '우리만을 위한 고유한 시간',
    'experience.ideal.title': '이상적 하루의 경험',
    'experience.ideal.subtitle': '스테이그라운드와 함께하기',
    
    // 매거진 상세 페이지
    'magazine.detail.hero.title': '매거진 제목',
    'magazine.detail.hero.subtitle': '매거진 부제목',
    'magazine.detail.description.title': '매거진 설명',
    'magazine.detail.description.content': '매거진 상세 내용이 여기에 들어갑니다. 이 섹션은 매거진의 주요 내용을 설명하는 부분입니다.',
    'magazine.detail.accommodation.title': '관련 숙소',
    'magazine.detail.accommodation.subtitle': '이 매거진과 관련된 숙소들을 확인해보세요.',
    'magazine.detail.banner.title': '특별한 경험',
    'magazine.detail.banner.subtitle': '스테이그라운드에서만 경험할 수 있는 특별한 시간',
    'magazine.detail.info.title': '상세 정보',
    'magazine.detail.info.location': '위치',
    'magazine.detail.info.address': '주소',
    'magazine.detail.info.contact': '연락처',
    'magazine.detail.info.email': '이메일',
    'magazine.detail.info.website': '웹사이트',
    'magazine.detail.navigation.previous': '이전',
    'magazine.detail.navigation.next': '다음',
    
    // 매거진 상세 페이지 테이블 라벨
    'magazine.detail.table.stay_name': '스테이명',
    'magazine.detail.table.type': '타입',
    'magazine.detail.table.capacity': '기준인원 / 최대인원',
    'magazine.detail.table.rooms': '객실수',
    'magazine.detail.table.checkin_checkout': '체크인 / 체크아웃',
    'magazine.detail.table.address': '주소',
    'magazine.detail.table.amenities': '부대시설',
    'magazine.detail.button.book_now': '예약하기',
    'magazine.detail.button.inquiry': '문의하기',
    
    // 숙소 상세 페이지 Point 섹션
    'accommodation.point1.title': '대나무가 전하는 치유의 소리',
    'accommodation.point1.description': '바람에 흩날리는 대나무숲의 소리에 집중해 보세요. 뭇별은 대나무로 둘러싸인 자연 속에 위치하여 머무는 내내 대나무의 싱그러운 초록빛을 누릴 수 있습니다. 뭇별의 담벼락이 되어주는 대나무는 침실, 거실, 화장실까지 그 싱그러운 빛을 내어주어 치유의 에너지를 전해줍니다. 특히 울창히 펼쳐진 대나무 숲과 그 끝에 보이는 삼척 바다, 뭇별의 자쿠지에서 맞이하는 경관은 오래도록 잊지 못할 치유가 되어줄 겁니다.',
    'accommodation.point2.title': '계절이 머무는 마당',
    'accommodation.point2.description': '프라이빗한 마당에는 사계절 내내 즐길 수 있는 온수풀이 마련되어 있습니다. 따뜻한 물에 몸을 담그고, 변화하는 자연의 풍경을 감상하며 여유로운 시간을 보낼 수 있습니다. 밤에는 별이 쏟아지는 하늘 아래에서 낭만적인 수영을 즐겨보세요. 마당 한가운데 자리 잡은 온수풀은 계절의 변화를 온몸으로 느낄 수 있는 특별한 공간입니다. 봄에는 새싹이 돋아나는 소리, 여름에는 매미 울음소리, 가을에는 낙엽이 떨어지는 소리, 겨울에는 고요한 적막함까지 모든 계절의 아름다움을 담고 있습니다.',
    'accommodation.point3.title': '미니멀한 디자인의 편안함',
    'accommodation.point3.description': '객실 내부는 미니멀한 디자인으로 꾸며져 있으며, 필요한 모든 편의시설을 갖추고 있어 편안한 휴식을 제공합니다. 통유리창을 통해 외부의 풍경을 내부로 끌어들이며, 어느 곳에서든 자연을 감상할 수 있습니다. 노출 콘크리트와 유리, 대나무를 활용하여 자연의 요소를 건축 안으로 들여온 디자인은 현대적이면서도 따뜻한 분위기를 연출합니다. 모든 공간에서 자연과의 조화를 느낄 수 있어 진정한 휴식과 치유의 시간을 보낼 수 있습니다.',
    
    // 홈페이지 매거진 섹션 데이터
    'magazine.home.title_46': '바쁜 일상에서 벗어나 즐기는 찰나의 휴식',
    'magazine.home.title_45': '한 걸음 쉬어가며 마주하는 평온, 서와정',
    'magazine.home.title_44': '바다와 대나무, 별의 울림이 깃든 공간',
    'magazine.home.title_43': '나를 위한 시간, 비우담',
  },
  en: {
    // Header
    'header.stayground': 'STAY GROUND.',
    'header.search': 'Search',
    'header.login': 'Login',
    'header.signup': 'Sign Up',
    'header.non_member_reservation': 'Non-member Reservation',
    
    // Homepage
    'home.summer_festa_coupon': 'Summer Festa 20,000 Won Coupon',
    'home.only_stayground': 'ONLY STAYGROUND',
    'home.pick': 'PICK',
    'home.earlybird': 'EARLYBIRD',
    'home.check_in_travel': 'CHECK IN TRAVEL',
    'home.promotion': 'PROMOTION',
    'home.magazine': 'MAGAZINE',
    'home.view_all': 'View All',
    
    // Search Filter
    'search.destination': 'Destination',
    'search.destination_placeholder': 'Search destination/accommodation',
    'search.checkin': 'Check-in',
    'search.checkin_placeholder': 'Search check-in date',
    'search.checkout': 'Check-out',
    'search.checkout_placeholder': 'Search check-out date',
    'search.people': 'People',
    'search.people_placeholder': 'Select people',
    'search.apply': 'Apply',
    'search.location': 'Location',
    'search.date': 'Date',
    
    // Stay Page
    'stay.title': 'CHECK IN TRAVEL',
    'stay.all_stays': 'All Stays',
    'stay.ending_soon': 'Ending Soon',
    'stay.private_stay': 'Private Stay',
    'stay.camping': 'Camping & Glamping',
    'stay.pet_friendly': 'Pet Friendly',
    'stay.pool': 'Pool',
    'stay.jacuzzi': 'Jacuzzi',
    'stay.hanok': 'Hanok',
    'stay.ocean_view': 'Ocean View',
    'stay.forest_view': 'Forest View',
    'stay.city_view': 'City View',
    'stay.harbor_view': 'Harbor View',
    'stay.sauna': 'Sauna',
    'stay.filter': 'Filter',
    'stay.sort': 'Recommended',
    'stay.sort_latest': 'Latest',
    'stay.sort_popular': 'Popular',
    'stay.sort_price_high': 'Price High',
    'stay.sort_price_low': 'Price Low',
    'stay.search_results': 'Search Results',
    'stay.accommodations': 'accommodations',
    
    // Common
    'common.adult': 'Adult',
    'common.child': 'Child',
    'common.infant': 'Infant',
    'common.person': '',
    'common.reset': 'Reset',
    'common.close': 'Close',
    'common.loading': 'Loading...',
    'common.inquiry': 'Inquiry',
    'common.back': 'Back',
    'common.share': 'Share',
    'common.copy_link': 'Copy Link',
    'common.kakao': 'KakaoTalk',
    'common.line': 'LINE',
    
    // Location
    'location.all': 'All',
    'location.seoul': 'Seoul',
    'location.busan': 'Busan',
    'location.daegu': 'Daegu',
    'location.incheon': 'Incheon',
    'location.daejeon': 'Daejeon',
    'location.gwangju': 'Gwangju',
    'location.ulsan': 'Ulsan',
    'location.gyeonggi': 'Gyeonggi',
    'location.gangwon': 'Gangwon',
    'location.chungnam': 'Chungnam',
    'location.chungbuk': 'Chungbuk',
    'location.jeonnam': 'Jeonnam',
    'location.jeonbuk': 'Jeonbuk',
    'location.gyeongnam': 'Gyeongnam',
    'location.gyeongbuk': 'Gyeongbuk',
    'location.jeju': 'Jeju',
    
    // Navigation
    'nav.stay': 'Stay',
    'nav.promotion': 'Promotion',
    'nav.earlybird': 'Earlybird',
    'nav.magazine': 'Magazine',
    'nav.about': 'by. STAYBILITY',
    
    // Accommodation Detail Page
    'accommodation.room_type': 'Room Type',
    'accommodation.standard_capacity': 'Standard 2 people (Max 6 people)',
    'accommodation.room_details': 'Bedroom(2) Bathroom(3) Living Room(1) Kitchen(1)',
    'accommodation.checkin_time': 'Check-in 15:00 - Check-out 11:00',
    'accommodation.per_night': '/ night',
    'accommodation.book_now': 'Book Now',
    'accommodation.points': 'Points',
    'accommodation.room_info': 'Room Information',
    'accommodation.amenities': 'All Room Amenities',
    'accommodation.view_all_amenities': 'View All',
    'accommodation.notice': 'Check Information',
    'accommodation.location_info': 'Location',
    'accommodation.rules': 'Rules',
    'accommodation.refund_policy': 'Refund Policy',
    'accommodation.safety': 'Safety',
    'accommodation.pricing': 'Pricing',
    'accommodation.contact_info': 'Contact',
    'accommodation.address': 'Address',
    'accommodation.phone': 'Phone',
    'accommodation.email': 'Email',
    'accommodation.basic_rate': 'Basic Rate',
    'accommodation.peak_rate': 'Peak Rate',
    'accommodation.experience': 'Experience',
    
    // Promotion Page
    'promotion.events': 'Events',
    'promotion.promotions': 'Promotions',
    
    // Earlybird Page
    'earlybird.title': 'EARLYBIRD',
    
    // Magazine Page
    'magazine.title': 'MAGAZINE',
    
    // Footer
    'footer.company': 'Company',
    'footer.about': 'About',
    'footer.team': 'Team',
    'footer.careers': 'Careers',
    'footer.press': 'Press',
    'footer.support': 'Support',
    'footer.help': 'Help',
    'footer.contact': 'Contact',
    'footer.terms': 'Terms',
    'footer.privacy': 'Privacy',
    'footer.cookies': 'Cookies',
    'footer.social': 'Social',
    'footer.facebook': 'Facebook',
    'footer.instagram': 'Instagram',
    'footer.twitter': 'Twitter',
    'footer.youtube': 'YouTube',
    
    // Accommodation Card
    'accommodation.max_capacity': 'Max',
    'accommodation.people': 'people',
    'accommodation.location_separator': ' | ',
    
    // Accommodation Detail Page Additional
    'accommodation.room_name': 'Mudbyeol',
    'accommodation.room_description': 'A space filled with the resonance of sea, bamboo, and stars',
    'accommodation.room_description_detail1': 'This is a private space open to the sea, bringing natural elements into architecture using exposed concrete, glass, and bamboo. The water space in the courtyard and the full-length windows connecting indoor and outdoor areas draw the external landscape into the interior, allowing you to enjoy nature from anywhere.',
    'accommodation.room_description_detail2': 'The interior of the room is decorated with minimal design and equipped with all necessary amenities to provide comfortable rest. When you enter the space, the first thing that greets visitors is the sound of bamboo swaying in the wind. This brings peace of mind like music played by nature.',
    'accommodation.room_description_detail3': 'You can experience complete rest by soaking in the indoor bathtub while looking at the bamboo forest outside the window. A hot spring is prepared in the private courtyard that can be enjoyed all year round. You can spend a leisurely time soaking in warm water and admiring the changing natural scenery.',
    'accommodation.booking_checkin': 'Check-in',
    'accommodation.booking_checkout': 'Check-out',
    'accommodation.booking_people': 'People',
    'accommodation.booking_adult': 'Adult',
    'accommodation.booking_people_count': '',
    'accommodation.hero_title_en': 'Rest in a cluster of stars',
    'accommodation.hero_title_kr': 'Rest in a cluster of stars',
    
    // Footer Company Information
    'footer.company_name': 'STAYGROUND',
    'footer.ceo': 'CEO',
    'footer.ceo_name': 'Jung Min-hyuk',
    'footer.phone': 'Phone',
    'footer.phone_number': '1588-6198',
    'footer.email': 'stayground@staybility.co.kr',
    'footer.address': 'Address',
    'footer.address_detail': '4F, 51 Hoam-ro, Buk-gu, Daegu',
    'footer.business_number': 'Business Registration',
    'footer.business_number_detail': '808-85-02772',
    'footer.commerce_number': 'E-commerce Registration',
    'footer.commerce_number_detail': '2024-Daegu Buk-gu-0886',
    'footer.tourism_number': 'Tourism Business Registration',
    'footer.tourism_number_detail': '2023-000005',
    'footer.disclaimer': 'STAYGROUND is an intermediary for e-commerce and is not a party to e-commerce transactions. Obligations and responsibilities related to product reservations, use, and refunds are with each seller.',
    'footer.copyright': 'Copyright © 2023 STAYBILITY All Rights Reserved.',
    
    // Accommodation Dummy Data
    'accommodation.names.neulimihak': 'Slow Aesthetics',
    'accommodation.names.dallyard': 'Dallyard',
    'accommodation.names.nuun_seop': 'Nuun Seop',
    'accommodation.names.forest_house': 'Forest House',
    'accommodation.names.ocean_view_pension': 'Ocean View Pension',
    'accommodation.names.mountain_villa': 'Mountain Villa',
    'accommodation.names.city_oasis': 'City Oasis',
    'accommodation.names.rural_life': 'Rural Life',
    'accommodation.names.healing_stay': 'Healing Stay',
    'accommodation.names.sensational_stay': 'Sensational Stay',
    'accommodation.names.peaceful_rest': 'Peaceful Rest',
    'accommodation.names.nature_stay': 'Nature Stay',
    'accommodation.names.healing_pension': 'Healing Pension',
    'accommodation.names.mountain_resort': 'Mountain Resort',
    'accommodation.names.ocean_near_stay': 'Ocean Near Stay',
    'accommodation.names.grid_jeju': 'Grid Jeju',
    'accommodation.names.jogak_night': 'Jogak Night',
    
    // Accommodation Descriptions
    'accommodation.descriptions.neulimihak': 'Neulimihak is a beautiful accommodation that embodies the history and culture of Gyeongju. Experience a special rest in a space where tradition and modernity harmonize.',
    'accommodation.descriptions.dallyard': 'Dallyard is a special accommodation that provides modern comfort in the beautiful nature of Jeju.',
    'accommodation.descriptions.nuun_seop': 'Nuun Seop is a beautiful accommodation where Jeju\'s tradition and modernity harmonize.',
    
    // Location Dummy Data
    'location.gyeongju': 'Gyeongju, Gyeongsangbuk-do',
    'location.jeju_seogwipo': 'Seogwipo, Jeju',
    'location.jeju_city': 'Jeju City, Jeju',
    'location.gapyeong': 'Gapyeong-gun, Gyeonggi-do',
    'location.pyeongchang': 'Pyeongchang-gun, Gangwon-do',
    'location.taean': 'Taean-gun, Chungcheongnam-do',
    'location.yeosu': 'Yeosu, Jeollanam-do',
    'location.geoje': 'Geoje, Gyeongsangnam-do',
    'location.gangneung': 'Gangneung, Gangwon-do',
    'location.danyang': 'Danyang-gun, Chungcheongbuk-do',
    'location.andong': 'Andong, Gyeongsangbuk-do',
    'location.chuncheon': 'Chuncheon, Gangwon-do',
    'location.gongju': 'Gongju, Chungcheongnam-do',
    'location.suncheon': 'Suncheon, Jeollanam-do',
    'location.tongyeong': 'Tongyeong, Gyeongsangnam-do',
    'location.sokcho': 'Sokcho, Gangwon-do',
    
    // Promotion Data
    'promotion.bosque_summer': 'Bosque Summer Promotion',
    'promotion.bosque_summer_desc': 'Special summer discount promotion',
    'promotion.bosque_summer_cta': 'Book Now',
    'promotion.jogak_night': 'Jogak Night September Promotion',
    'promotion.jogak_night_desc': 'Limited September special promotion',
    'promotion.jogak_night_cta': 'Reserve',
    'promotion.summer_festa': 'STAYGROUND Summer Festa',
    'promotion.summer_festa_desc': 'Special summer festival event',
    'promotion.summer_festa_cta': 'Get Coupon',
    'promotion.summer_festa_detail': 'We present special benefits from STAYGROUND to those preparing for summer vacation. Enjoy a more special summer vacation with a 20,000 won discount coupon!',
    'promotion.family_month': 'Family Month Travel Support',
    'promotion.family_month_desc': 'Get 20,000 won coupon',
    'promotion.family_month_detail': 'In celebration of Family Month in May, we present a 20,000 won discount coupon that can be applied when reserving all spaces listed on STAYGROUND. Enjoy a special rest with your loved ones, along with STAYGROUND\'s gift!',
    'promotion.kb_pay': 'KB Pay Gift! [5th Round]',
    'promotion.kb_pay_desc': 'Good weather for travel, wondering where to go for a sentimental stay? KB Pay provides it for free.',
    'promotion.kb_pay_detail': 'Good weather for travel, wondering where to go for a sentimental stay? KB Pay provides it for free. Get additional benefits when paying with KB Pay!',
    'common.view_more': 'View More',
    
    // PICK Section Data
    'pick.title_1': 'Peacefully Settled in Roundness',
    'pick.subtitle_1': 'Onwon',
    'pick.title_2': 'Peacefully Settled in Roundness',
    'pick.subtitle_2': 'Onwon',
    'pick.title_3': 'Peacefully Settled in Roundness',
    'pick.subtitle_3': 'Onwon',
    'pick.title_4': 'Peacefully Settled in Roundness',
    'pick.subtitle_4': 'Onwon',
    'pick.title_5': 'Peacefully Settled in Roundness',
    'pick.subtitle_5': 'Onwon',
    'pick.title_6': 'Peacefully Settled in Roundness',
    'pick.subtitle_6': 'Onwon',
    'pick.title_7': 'Peacefully Settled in Roundness',
    'pick.subtitle_7': 'Onwon',
    'pick.title_8': 'Peacefully Settled in Roundness',
    'pick.subtitle_8': 'Onwon',
    'pick.title_9': 'Peacefully Settled in Roundness',
    'pick.subtitle_9': 'Onwon',
    'pick.title_10': 'Peacefully Settled in Roundness',
    'pick.subtitle_10': 'Onwon',
    
    // Earlybird Data
    'earlybird.title_text': 'Earlybird Special Price',
    'earlybird.description': 'Limited quantity special discount',
    'earlybird.cta': 'Book Now',
    
    // Magazine Data
    'magazine.seowajeong': 'Seowajeong',
    'magazine.seowajeong_desc': 'A space where tradition meets modernity',
    'magazine.magazine_1': 'Magazine Issue 1',
    'magazine.magazine_2': 'Magazine Issue 2',
    'magazine.magazine_3': 'Magazine Issue 3',
    'magazine.magazine_4': 'Magazine Issue 4',
    'magazine.title_46': 'A moment of rest enjoyed away from busy daily life',
    'magazine.title_45': 'Special rest with the sea, tranquility by the beach',
    'magazine.title_44': 'Peace found in the forest, rest with nature',
    'magazine.title_43': 'Time for myself, Biudam',
    'magazine.title_42': 'Inner peace found in nature',
    'magazine.title_41': 'New experiences found away from the city',
    'magazine.title_40': 'Perfect rest forgetting time',
    'magazine.title_39': 'The moment of discovering the beauty of small daily life',
    'magazine.title_38': 'Free travel with the wind',
    'magazine.title_37': 'Romantic night under the stars',
    'magazine.title_36': 'Healing where mountains and sea meet',
    'magazine.title_35': 'A space where tradition and modernity harmonize',
    'magazine.title_34': 'A special space feeling seasonal changes',
    'magazine.title_33': 'Healing time finding mental leisure',
    'magazine.title_32': 'Eco-friendly travel with nature',
    'magazine.title_31': 'New experiences found away from the city',
    
    // Magazine Page
    'magazine.page_title': 'Magazine',
    
    // Accommodation Detail Page
    'accommodation.room_info.standard_capacity': 'Standard Capacity',
    'accommodation.room_info.checkin': 'Check-in',
    'accommodation.room_info.checkout': 'Check-out',
    'accommodation.room_info.area': 'Room Area',
    'accommodation.room_info.spaces': 'Room Spaces',
    'accommodation.room_info.bed_types': 'Bed Types',
    'accommodation.room_info.title': 'Room Information',
    'accommodation.room_info.people': 'people',
    'accommodation.room_info.max_people': 'Max',
    'accommodation.amenities.title': 'All Room Inclusions',
    'accommodation.amenities.view_all': 'View All',
    'accommodation.amenities.hair_dryer': 'Hair Dryer',
    'accommodation.amenities.coffee_machine': 'Coffee Machine',
    'accommodation.amenities.bathroom_amenities': 'Bathroom Amenities',
    'accommodation.amenities.condiments': 'Condiments',
    'accommodation.amenities.outdoor_slippers': 'Outdoor Slippers',
    'accommodation.amenities.microwave': 'Microwave',
    'accommodation.amenities.hand_sanitizer': 'Hand Sanitizer',
    'accommodation.amenities.coffee_pot': 'Coffee Pot',
    'accommodation.amenities.refrigerator': 'Refrigerator',
    'accommodation.amenities.air_conditioner': 'Air Conditioner',
    'accommodation.amenities.tv': 'TV',
    'accommodation.amenities.induction': 'Induction Cooktop',
    'accommodation.amenities.cooking_utensils': 'Cooking Utensils',
    'accommodation.amenities.tableware': 'Tableware',
    'accommodation.amenities.wine_opener': 'Wine Opener',
    'accommodation.amenities.wine_glass': 'Wine Glass',
    'accommodation.amenities.towel': 'Towel',
    'accommodation.amenities.diffuser': 'Diffuser',
    'accommodation.info.title': 'Please check the information',
    'accommodation.info.location': 'Location Guide',
    'accommodation.info.rules': 'Usage Rules',
    'accommodation.info.refund': 'Refund Policy',
    'accommodation.info.safety': 'Safety Facilities',
    'accommodation.info.pricing': 'Pricing Policy',
    'accommodation.info.address': 'Address',
    'accommodation.info.contact': 'Contact',
    'accommodation.info.email': 'Email',
    'accommodation.pricing.off_peak': 'Off-Peak',
    'accommodation.pricing.peak': 'Peak',
    'accommodation.pricing.high_peak': 'High Peak',
    'accommodation.pricing.weekday': 'Weekday',
    'accommodation.pricing.weekend': 'Weekend',
    'accommodation.pricing.category': 'Category',
    'accommodation.pricing.note': 'Please check detailed rates after selecting your schedule.',
    'accommodation.inquiry': 'Inquiry',
    
    // Accommodation Detail Page Tab Content
    'accommodation.tab.room_spaces': 'Bedroom(1), Bathroom(2), Living Room(1), Kitchen(1)',
    'accommodation.tab.checkin_checkout': 'Check-in and Check-out',
    'accommodation.tab.checkin_time': 'Check-in is at 3 PM, check-out is at 11 AM.',
    'accommodation.tab.standard_capacity_detail': 'Standard capacity is 2 people, maximum 6 people (including infants). Adults and children are limited to 5 people. No check-in is allowed if the maximum capacity is exceeded.',
    'accommodation.tab.child_age': 'Child age limit is up to 12 years old.',
    'accommodation.tab.visitor_policy': 'Non-guest visitors can use the facility with additional charges within the standard capacity (not available if capacity is exceeded).',
    'accommodation.tab.pet_policy': 'We love pets, but pets are not allowed as this is a shared space used by many people.',
    'accommodation.tab.cleaning_service': 'Cleaning service is not provided for extended stays.',
    
    // Rules Tab Content
    'accommodation.tab.room': 'Room',
    'accommodation.tab.room_kids_warning': 'This is not a Yes-kids zone or space designed for children, so special attention from guardians is required. We are not responsible for accidents due to carelessness. (Please be especially careful in areas such as jacuzzi, swimming pool, stairs, etc.)',
    'accommodation.tab.room_cooking_ban': 'Cooking meat, fish, fried foods, or any food with strong odors or oily foods is strictly prohibited in the room.',
    'accommodation.tab.room_damage_policy': 'We strictly manage equipment before check-in. Please check for any damaged parts we have mentioned in advance. For severe contamination, tube damage, dye contamination, or other difficult-to-repair damage that occurs after check-in, we may charge the purchase price of the same product or repair costs. (Please avoid frequent contamination cases such as dyeing, children\'s slime play, etc.)',
    'accommodation.tab.room_wood_care': 'The dining table and sink are made of wood and are vulnerable to fire. Please be careful not to place heated pots directly on them when cooking.',
    'accommodation.tab.room_slippers': 'Please use indoor slippers only indoors and outdoor slippers only in the garden.',
    
    'accommodation.tab.outdoor_safety': 'Outdoor Activities and Safety',
    'accommodation.tab.outdoor_fire_ban': 'Due to fire hazards, smoking, candles, fireworks, personal stoves, butane gas, etc. are absolutely prohibited in the garden.',
    
    'accommodation.tab.jacuzzi_guide': 'Jacuzzi Guide',
    'accommodation.tab.jacuzzi_notice': 'Please refer to the information provided in the jacuzzi.',
    'accommodation.tab.jacuzzi_bath_salt': 'Using bath salts other than the prepared ones may stain the tub, so all personal bath salt use is prohibited. If staining occurs after using personal bath salts, cleaning fees may be charged, so please be careful.',
    'accommodation.tab.jacuzzi_water_overflow': 'Please be careful not to overflow the bath water. (Water filling takes 40 minutes)',
    'accommodation.tab.jacuzzi_surface': 'After non-slip construction of the jacuzzi interior, we have taken maximum safety measures (rounded edges), but it may feel rough, so please wear light clothes or swimsuits when using.',
    'accommodation.tab.jacuzzi_children': 'When infants and children use it, please use it with a guardian.',
    'accommodation.tab.jacuzzi_drain': 'Please completely drain the water after use.',
    'accommodation.tab.jacuzzi_plug': 'Please close the jacuzzi plug with the handle facing upward, and if you accidentally close it upside down, please don\'t panic and contact us.',
    
    'accommodation.tab.barbecue_guide': 'Barbecue Guide',
    'accommodation.tab.barbecue_equipment': 'If you add barbecue as an option, an electric grill will be prepared.',
    'accommodation.tab.barbecue_weather': 'Use is absolutely impossible during snow, rain, or strong winds',
    'accommodation.tab.barbecue_shopping': 'Please check the weather on the day of check-in and buy meat',
    'accommodation.tab.barbecue_cleanup': 'After using the barbecue grill, please wipe it lightly with kitchen towels and be sure to unplug the cord (fire hazard)',
    
    'accommodation.tab.pool_guide': 'Swimming Pool Guide',
    'accommodation.tab.pool_temperature': 'The swimming pool is maintained at 32-33 degrees lukewarm water.',
    'accommodation.tab.pool_weather_effect': 'Due to the nature of outdoor swimming pools, water temperature is greatly affected by weather and temperature, so the perceived temperature may be different.',
    'accommodation.tab.pool_depth': 'The swimming pool interior is constructed with non-slip material in a gradually deepening form, but diving in can cause safety accidents, so please be especially careful.',
    'accommodation.tab.pool_diaper': 'Infants should wear waterproof diapers before using.',
    'accommodation.tab.pool_debris': 'Due to the nature of outdoor swimming pools, debris such as fallen leaves and insects may enter. Please use the provided net to remove them before using.',
    'accommodation.tab.pool_water_quality': 'Water quality is managed through filtration systems and periodic cleaning is conducted, so please use it with confidence.',
    'accommodation.tab.pool_contamination': 'Please absolutely avoid adding bath salts and foreign substances (urination, bath salts, flower petals, foam, sand) to the swimming pool.',
    'accommodation.tab.pool_depth_range': 'The swimming pool depth is 0.2m~1.2m. Please cooperate so that children can only use it when accompanied by a guardian, and be careful of safety accidents.',
    'accommodation.tab.pool_weather_limit': 'There may be usage restrictions due to weather deterioration such as heavy snow and typhoons. This is a measure for the safety of guests, so please understand.',
    'accommodation.tab.pool_hours': 'There is no time limit for swimming pool use, but lukewarm water is maintained from 4:00 to 9:00.',
    
    'accommodation.tab.ethanol_fire': 'Ethanol Fire',
    'accommodation.tab.ethanol_reservation': 'Ethanol fire is prepared for advance reservations.',
    'accommodation.tab.ethanol_usage': 'After evenly injecting the prepared ethanol into the injection port and lighting it, it will burn within minutes.',
    'accommodation.tab.ethanol_danger': 'Adding ethanol during use is very dangerous, so please avoid adding ethanol during use.',
    'accommodation.tab.ethanol_weather': 'It may be limited depending on weather conditions. It is not available on rainy days',
    
    'accommodation.tab.supplies': 'Main Building/Guest House Supplies',
    'accommodation.tab.main_building': 'Main Building',
    'accommodation.tab.seasoning': 'Seasoning (soy sauce, oil, sugar, salt)',
    'accommodation.tab.kitchen_appliances': 'Toaster, electric kettle, capsule coffee machine, induction, water purifier, microwave',
    'accommodation.tab.entertainment': 'Dynaudio Brown speaker, standby TV (Netflix)',
    'accommodation.tab.slippers': 'Indoor and outdoor slippers (white)',
    'accommodation.tab.laundry': 'Laundry drying rack, tube air pump',
    'accommodation.tab.tubes': 'Adult tube 1, child tube 1 (upon request)',
    'accommodation.tab.beach_towel': 'Beach towel',
    'accommodation.tab.insect_repellent': 'Mosquito repellent, mosquito incense, insect repellent, pain relief spray',
    'accommodation.tab.chargers': 'Chargers (C-type, 5-pin, iPhone)',
    'accommodation.tab.baby_chair': 'Baby chair (provided upon request)',
    'accommodation.tab.grill_table': 'Electric grill / outdoor folding table (upon request)',
    'accommodation.tab.bathroom_supplies': 'Toothbrush, toothpaste, bathroom amenities, bath salts',
    'accommodation.tab.bathrobe': 'Shower robe is only provided upon request before check-in',
    
    'accommodation.tab.guest_house': 'Guest House',
    'accommodation.tab.marshall_speaker': 'Marshall speaker',
    
    'accommodation.tab.supplies_note': '*Please prepare baby dishes, children\'s items, foam cleanser, and cosmetics in addition to the provided items.',
    'accommodation.tab.damage_note': '*All equipment is checked for normal operation before check-in, and compensation may be required if damage is found at check-out',
    
    // Refund Policy Tab Content
    'accommodation.tab.refund_date': 'Base Date',
    'accommodation.tab.refund_amount': 'Refund Amount',
    'accommodation.tab.refund_20_days': 'Up to 20 days before check-in',
    'accommodation.tab.refund_14_days': 'Up to 14 days before check-in',
    'accommodation.tab.refund_8_days': 'Up to 8 days before check-in',
    'accommodation.tab.refund_7_days': 'Up to 7 days before check-in',
    'accommodation.tab.refund_6_days': 'Up to 6 days before check-in',
    'accommodation.tab.refund_5_days': 'Up to 5 days before check-in',
    'accommodation.tab.refund_4_days': 'Up to 4 days before check-in',
    'accommodation.tab.refund_3_days': 'From 3 days before check-in',
    'accommodation.tab.refund_100': '100% refund',
    'accommodation.tab.refund_90': '90% refund',
    'accommodation.tab.refund_80': '80% refund',
    'accommodation.tab.refund_70': '70% refund',
    'accommodation.tab.refund_60': '60% refund',
    'accommodation.tab.refund_50': '50% refund',
    'accommodation.tab.refund_40': '40% refund',
    'accommodation.tab.refund_no': 'No refund',
    'accommodation.tab.refund_note': 'Refund fees follow the refund policy regardless of cancellation within 24 hours after reservation completion',
    
    // Safety Facilities Tab Content
    'accommodation.tab.fire_extinguisher': 'Fire Extinguisher',
    'accommodation.tab.fire_main_building': 'Main building - 1st floor bathroom in room',
    'accommodation.tab.fire_guest_house': 'Guest house - storage under sink',
    'accommodation.tab.first_aid': 'First Aid',
    'accommodation.tab.first_aid_items': 'Pain relief spray, mosquito repellent, band-aids, disinfectant',
    
    // Pricing Policy Tab Content
    'accommodation.pricing.basic_rate': 'Basic Rate',
    'accommodation.pricing.peak_season_rate': 'Peak Season Rate',
    'common.currency_unit': 'KRW',
    
    // Experience Section
    'experience.yeoju.title': 'Yeoju County : Dongcheon',
    'experience.yeoju.subtitle': 'A refreshing night in beautiful mountain scenery',
    'experience.layr.title': 'LAYR',
    'experience.layr.subtitle': 'Layer Hanok House',
    'experience.layr.description': 'A space that awakens inner taste',
    'experience.timezone.title': 'Unique Timezone',
    'experience.timezone.subtitle': 'Unique time just for us',
    'experience.ideal.title': 'Ideal Day Experience',
    'experience.ideal.subtitle': 'Experience with Stayground',
    
    // Magazine Detail Page
    'magazine.detail.hero.title': 'Magazine Title',
    'magazine.detail.hero.subtitle': 'Magazine Subtitle',
    'magazine.detail.description.title': 'Magazine Description',
    'magazine.detail.description.content': 'Magazine detailed content goes here. This section describes the main content of the magazine.',
    
    // Stay Page Search Bar Translation
    'stay.search.destination': 'Destination',
    'stay.search.destination_placeholder': 'Search destination/accommodation',
    'stay.search.checkin': 'Check-in',
    'stay.search.checkin_placeholder': 'Search check-in date',
    'stay.search.checkout': 'Check-out',
    'stay.search.checkout_placeholder': 'Search check-out date',
    'stay.search.people': 'People',
    'stay.search.people_placeholder': 'Select people',
    'stay.search.apply': 'Apply',
    'stay.search.adult': 'Adult',
    'stay.search.child': 'Child',
    'stay.search.infant': 'Infant',
    'stay.search.people_count': 'people',
    
    // Stay Page Icon Grid Translation
    'stay.icons.all_stays': 'All Stays',
    'stay.icons.ending_soon': 'Ending Soon',
    'stay.icons.private_stay': 'Private Stay',
    'stay.icons.camping': 'Camping & Glamping',
    'stay.icons.pet_friendly': 'Pet Friendly',
    'stay.icons.pool': 'Pool',
    'stay.icons.jacuzzi': 'Jacuzzi',
    'stay.icons.hanok': 'Hanok',
    'stay.icons.ocean_view': 'Ocean View',
    'stay.icons.forest_view': 'Forest View',
    'stay.icons.city_view': 'City View',
    'stay.icons.harbor_view': 'Harbor View',
    'stay.icons.sauna': 'Sauna',
    
    // Stay Page Filter Translation
    'stay.filter.recommended': 'Recommended',
    'stay.filter.latest': 'Latest',
    'stay.filter.popular': 'Popular',
    'stay.filter.price_high': 'Price High to Low',
    'stay.filter.price_low': 'Price Low to High',
    'stay.filter.filter': 'Filter',
    'stay.filter.reset': 'Reset',
    'stay.filter.apply': 'Apply',
    
    // Stay Page Location Translation
    'stay.location.all': 'All',
    'stay.location.seoul': 'Seoul',
    'stay.location.busan': 'Busan',
    'stay.location.daegu': 'Daegu',
    'stay.location.incheon': 'Incheon',
    'stay.location.daejeon': 'Daejeon',
    'stay.location.gwangju': 'Gwangju',
    'stay.location.ulsan': 'Ulsan',
    'stay.location.gyeonggi': 'Gyeonggi-do',
    'stay.location.gangwon': 'Gangwon-do',
    'stay.location.chungnam': 'Chungcheongnam-do',
    'stay.location.chungbuk': 'Chungcheongbuk-do',
    'stay.location.jeonnam': 'Jeollanam-do',
    'stay.location.jeonbuk': 'Jeollabuk-do',
    'stay.location.gyeongnam': 'Gyeongsangnam-do',
    'stay.location.gyeongbuk': 'Gyeongsangbuk-do',
    'stay.location.jeju': 'Jeju-do',
    
    // Stay Page Amenities Translation
    'stay.amenities.four_season_pool': 'Four Season Pool',
    'stay.amenities.bbq': 'BBQ',
    'stay.amenities.outdoor_bath': 'Outdoor Bath',
    'stay.amenities.fire_pit': 'Fire Pit',
    'stay.amenities.walking_trail': 'Walking Trail',
    'stay.amenities.terrace': 'Terrace',
    'stay.amenities.breakfast': 'Breakfast',
    'stay.amenities.smart_home': 'Smart Home',
    'stay.amenities.fitness': 'Fitness (Gym)',
    'stay.amenities.yoga': 'Yoga',
    'stay.amenities.karaoke': 'Karaoke',
    'magazine.detail.accommodation.title': 'Related Accommodations',
    'magazine.detail.accommodation.subtitle': 'Check out the accommodations related to this magazine.',
    'magazine.detail.banner.title': 'Special Experience',
    'magazine.detail.banner.subtitle': 'Special time you can only experience at Stayground',
    'magazine.detail.info.title': 'Detailed Information',
    'magazine.detail.info.location': 'Location',
    'magazine.detail.info.address': 'Address',
    'magazine.detail.info.contact': 'Contact',
    'magazine.detail.info.email': 'Email',
    'magazine.detail.info.website': 'Website',
    'magazine.detail.navigation.previous': 'Previous',
    'magazine.detail.navigation.next': 'Next',
    
    // Magazine Detail Page Table Labels
    'magazine.detail.table.stay_name': 'Stay Name',
    'magazine.detail.table.type': 'Type',
    'magazine.detail.table.capacity': 'Standard / Max Capacity',
    'magazine.detail.table.rooms': 'Number of Rooms',
    'magazine.detail.table.checkin_checkout': 'Check-in / Check-out',
    'magazine.detail.table.address': 'Address',
    'magazine.detail.table.amenities': 'Facilities',
    'magazine.detail.button.book_now': 'Book Now',
    'magazine.detail.button.inquiry': 'Inquiry',
    
    // Accommodation Detail Page Point Section
    'accommodation.point1.title': 'The Healing Sound of Bamboo',
    'accommodation.point1.description': 'Focus on the sound of bamboo forest swaying in the wind. Mootbyeol is located in nature surrounded by bamboo, allowing you to enjoy the fresh green color of bamboo throughout your stay. The bamboo that serves as Mootbyeol\'s wall provides its fresh light to the bedroom, living room, and bathroom, transmitting healing energy. Especially the lush bamboo forest and the Samcheok sea visible at its end, and the scenery you encounter in Mootbyeol\'s jacuzzi will be an unforgettable healing experience.',
    'accommodation.point2.title': 'A Courtyard Where Seasons Stay',
    'accommodation.point2.description': 'A private courtyard features a hot spring pool that can be enjoyed throughout all four seasons. Soak in the warm water, admire the changing natural scenery, and spend leisurely time. At night, enjoy romantic swimming under the starry sky. The hot spring pool located in the center of the courtyard is a special space where you can feel the changes of seasons with your whole body. It contains all the beauty of every season: the sound of new sprouts in spring, cicada songs in summer, the sound of falling leaves in autumn, and the peaceful silence of winter.',
    'accommodation.point3.title': 'Comfort of Minimalist Design',
    'accommodation.point3.description': 'The room interior is decorated with minimalist design and equipped with all necessary amenities to provide comfortable rest. Through floor-to-ceiling windows, external scenery is brought inside, allowing you to enjoy nature from anywhere. The design utilizing exposed concrete, glass, and bamboo brings natural elements into the architecture, creating a modern yet warm atmosphere. You can feel harmony with nature in every space, allowing for true rest and healing time.',
    
    // Homepage Magazine Section Data
    'magazine.home.title_46': 'A moment of rest enjoyed away from busy daily life',
    'magazine.home.title_45': 'Peace encountered while taking a step back, Seowajeong',
    'magazine.home.title_44': 'A space filled with the resonance of sea, bamboo, and stars',
    'magazine.home.title_43': 'Time for myself, Biudam',
  },

  zh: {
    // 头部
    'header.stayground': 'STAY GROUND.',
    'header.search': '搜索',
    'header.login': '登录',
    'header.signup': '注册',
    'header.non_member_reservation': '非会员预约查询',
    
    // 首页
    'home.summer_festa_coupon': '夏日庆典2万韩元优惠券',
    'home.only_stayground': 'ONLY STAYGROUND',
    'home.pick': 'PICK',
    'home.earlybird': 'EARLYBIRD',
    'home.check_in_travel': 'CHECK IN TRAVEL',
    'home.promotion': 'PROMOTION',
    'home.magazine': 'MAGAZINE',
    'home.view_all': '查看全部',
    
    // 搜索过滤器
    'search.destination': '目的地',
    'search.destination_placeholder': '搜索目的地/住宿',
    'search.checkin': '入住',
    'search.checkin_placeholder': '搜索入住日期',
    'search.checkout': '退房',
    'search.checkout_placeholder': '搜索退房日期',
    'search.people': '人数',
    'search.people_placeholder': '选择人数',
    'search.apply': '应用',
    'search.location': '地区',
    'search.date': '日期',
    
    // 住宿页面
    'stay.title': 'CHECK IN TRAVEL',
    'stay.all_stays': '所有住宿',
    'stay.ending_soon': '即将结束',
    'stay.private_stay': '私人住宿',
    'stay.camping': '露营&豪华露营',
    'stay.pet_friendly': '宠物友好',
    'stay.pool': '游泳池',
    'stay.jacuzzi': '按摩浴缸',
    'stay.hanok': '韩屋',
    'stay.ocean_view': '海景',
    'stay.forest_view': '森林景观',
    'stay.city_view': '城市景观',
    'stay.harbor_view': '港口景观',
    'stay.sauna': '桑拿',
    'stay.filter': '过滤器',
    'stay.sort': '推荐',
    'stay.sort_latest': '最新',
    'stay.sort_popular': '热门',
    'stay.sort_price_high': '价格从高到低',
    'stay.sort_price_low': '价格从低到高',
    'stay.search_results': '搜索结果',
    'stay.accommodations': '个住宿',
    
    // 通用
    'common.adult': '成人',
    'common.child': '儿童',
    'common.infant': '婴儿',
    'common.person': '人',
    'common.reset': '重置',
    'common.close': '关闭',
    'common.loading': '加载中...',
    'common.inquiry': '咨询',
    'common.back': '返回',
    'common.share': '分享',
    'common.copy_link': '复制链接',
    'common.kakao': 'KakaoTalk',
    'common.line': 'LINE',
    
    // 地区
    'location.all': '全部',
    'location.seoul': '首尔',
    'location.busan': '釜山',
    'location.daegu': '大邱',
    'location.incheon': '仁川',
    'location.daejeon': '大田',
    'location.gwangju': '光州',
    'location.ulsan': '蔚山',
    'location.gyeonggi': '京畿道',
    'location.gangwon': '江原道',
    'location.chungnam': '忠清南道',
    'location.chungbuk': '忠清北道',
    'location.jeonnam': '全罗南道',
    'location.jeonbuk': '全罗北道',
    'location.gyeongnam': '庆尚南道',
    'location.gyeongbuk': '庆尚北道',
    'location.jeju': '济州道',
    
    // 导航
    'nav.stay': '住宿',
    'nav.promotion': '促销',
    'nav.earlybird': '早鸟',
    'nav.magazine': '杂志',
    'nav.about': 'by. STAYBILITY',
    
    // 住宿详情页
    'accommodation.room_type': '房型',
    'accommodation.standard_capacity': '标准2人 (最多6人)',
    'accommodation.room_details': '卧室(2) 浴室(3) 客厅(1) 厨房(1)',
    'accommodation.checkin_time': '入住 15:00 - 退房 11:00',
    'accommodation.per_night': '/ 晚',
    'accommodation.book_now': '立即预订',
    'accommodation.points': '要点',
    'accommodation.room_info': '房间信息',
    'accommodation.amenities': '所有房间设施',
    'accommodation.view_all_amenities': '查看全部',
    'accommodation.notice': '查看信息',
    'accommodation.location_info': '位置',
    'accommodation.rules': '规则',
    'accommodation.refund_policy': '退款政策',
    'accommodation.safety': '安全',
    'accommodation.pricing': '定价',
    'accommodation.contact_info': '联系',
    'accommodation.address': '地址',
    'accommodation.phone': '电话',
    'accommodation.email': '邮箱',
    'accommodation.basic_rate': '基本价格',
    'accommodation.peak_rate': '旺季价格',
    'accommodation.experience': '体验',
    
    // 促销页面
    'promotion.events': '活动',
    'promotion.promotions': '促销',
    
    // 早鸟页面
    'earlybird.title': 'EARLYBIRD',
    
    // 杂志页面
    'magazine.title': 'MAGAZINE',
    
    // 页脚
    'footer.company': '公司',
    'footer.about': '关于我们',
    'footer.team': '团队',
    'footer.careers': '招聘',
    'footer.press': '新闻',
    'footer.support': '客户支持',
    'footer.help': '帮助',
    'footer.contact': '联系我们',
    'footer.terms': '条款',
    'footer.privacy': '隐私',
    'footer.cookies': 'Cookie政策',
    'footer.social': '社交',
    'footer.facebook': 'Facebook',
    'footer.instagram': 'Instagram',
    'footer.twitter': 'Twitter',
    'footer.youtube': 'YouTube',
    
    // 住宿卡片
    'accommodation.max_capacity': '最多',
    'accommodation.people': '人',
    'accommodation.location_separator': ' | ',
    
    // 住宿详情页附加
    'accommodation.room_name': '木别',
    'accommodation.room_description': '充满海洋、竹子和星星共鸣的空间',
    'accommodation.room_description_detail1': '这是一个面向海洋的私人空间，使用裸露的混凝土、玻璃和竹子将自然元素带入建筑。庭院中的水空间和连接室内外的落地窗将外部景观引入室内，让您可以从任何地方欣赏自然。',
    'accommodation.room_description_detail2': '房间内部采用极简设计装饰，配备所有必要的便利设施，提供舒适的休息。当您进入空间时，首先迎接访客的是竹子在风中摇曳的声音。这就像大自然演奏的音乐一样带来心灵的平静。',
    'accommodation.room_description_detail3': '您可以浸泡在室内浴缸中，同时看着窗外的竹林，体验完全的休息。私人庭院中准备了全年都可以享受的温泉。您可以浸泡在温水中，欣赏变化的自然风景，度过悠闲的时光。',
    'accommodation.booking_checkin': '入住',
    'accommodation.booking_checkout': '退房',
    'accommodation.booking_people': '人数',
    'accommodation.booking_adult': '成人',
    'accommodation.booking_people_count': '人',
    'accommodation.hero_title_en': 'Rest in a cluster of stars',
    'accommodation.hero_title_kr': '在星群中休息',
    
    // 页脚公司信息
    'footer.company_name': 'STAYGROUND',
    'footer.ceo': '首席执行官',
    'footer.ceo_name': '郑敏赫',
    'footer.phone': '电话',
    'footer.phone_number': '1588-6198',
    'footer.email': 'stayground@staybility.co.kr',
    'footer.address': '地址',
    'footer.address_detail': '大邱广域市北区虎岩路51号4楼',
    'footer.business_number': '营业执照号',
    'footer.business_number_detail': '808-85-02772',
    'footer.commerce_number': '电子商务注册号',
    'footer.commerce_number_detail': '2024-大邱北区-0886',
    'footer.tourism_number': '旅游业务注册号',
    'footer.tourism_number_detail': '2023-000005',
    'footer.disclaimer': 'STAYGROUND是电子商务中介，不是电子商务交易的当事方。与产品预订、使用和退款相关的义务和责任由各卖家承担。',
    'footer.copyright': '版权所有 © 2023 STAYBILITY',
    
    // 住宿虚拟数据
    'accommodation.names.neulimihak': '慢美学',
    'accommodation.names.dallyard': '达利雅德',
    'accommodation.names.nuun_seop': '努恩瑟普',
    'accommodation.names.forest_house': '森林之家',
    'accommodation.names.ocean_view_pension': '海景民宿',
    'accommodation.names.mountain_villa': '山间别墅',
    'accommodation.names.city_oasis': '城市绿洲',
    'accommodation.names.rural_life': '田园生活',
    'accommodation.names.healing_stay': '疗愈住宿',
    'accommodation.names.sensational_stay': '感性住宿',
    'accommodation.names.peaceful_rest': '和平休息',
    'accommodation.names.nature_stay': '自然住宿',
    'accommodation.names.healing_pension': '疗愈度假屋',
    'accommodation.names.mountain_resort': '山地度假村',
    'accommodation.names.ocean_near_stay': '海边住宿',
    'accommodation.names.grid_jeju': '网格济州',
    'accommodation.names.jogak_night': '雕刻夜',
    
    // 住宿描述
    'accommodation.descriptions.neulimihak': '慢美学是承载庆州历史和文化的美丽住宿。在传统与现代和谐的空间中体验特别的休息。',
    'accommodation.descriptions.dallyard': '达利雅德是在济州美丽自然中提供现代舒适的特殊住宿。',
    'accommodation.descriptions.nuun_seop': '躺卧的柴是济州传统与现代和谐的美丽住宿。',
    
    // 位置虚拟数据
    'location.gyeongju': '庆尚北道庆州市',
    'location.jeju_seogwipo': '济州岛西归浦市',
    'location.jeju_city': '济州岛济州市',
    'location.gapyeong': '京畿道加平郡',
    'location.pyeongchang': '江原道平昌郡',
    'location.taean': '忠清南道泰安郡',
    'location.yeosu': '全罗南道丽水市',
    'location.geoje': '庆尚南道巨济市',
    'location.gangneung': '江原道江陵市',
    'location.danyang': '忠清北道丹阳郡',
    'location.andong': '庆尚北道安东市',
    'location.chuncheon': '江原道春川市',
    'location.gongju': '忠清南道公州市',
    'location.suncheon': '全罗南道顺天市',
    'location.tongyeong': '庆尚南道统营市',
    'location.sokcho': '江原道束草市',
    
    // 促销数据
    'promotion.bosque_summer': '博斯克夏季促销',
    'promotion.bosque_summer_desc': '夏季特别折扣促销',
    'promotion.bosque_summer_cta': '立即预订',
    'promotion.jogak_night': '雕刻夜9月促销',
    'promotion.jogak_night_desc': '9月限定特别促销',
    'promotion.jogak_night_cta': '预订',
    'promotion.summer_festa': 'STAYGROUND夏季庆典',
    'promotion.summer_festa_desc': '夏季庆典特别活动',
    'promotion.summer_festa_cta': '领取优惠券',
    'promotion.summer_festa_detail': '为准备夏季假期的各位提供STAYGROUND特别优惠。用2万韩元优惠券享受更特别的夏季假期！',
    'promotion.family_month': '家庭月旅行支援',
    'promotion.family_month_desc': '领取2万韩元优惠券',
    'promotion.family_month_detail': '为迎接5月家庭月，我们为STAYGROUND入驻的所有空间预订时提供2万韩元优惠券。与爱的人一起享受特别休息，与STAYGROUND的礼物一起！',
    'promotion.kb_pay': 'KB Pay礼物！[第5轮]',
    'promotion.kb_pay_desc': '适合旅行的好天气，为感性住宿去哪里而烦恼吗？KB Pay免费提供。',
    'promotion.kb_pay_detail': '适合旅行的好天气，为感性住宿去哪里而烦恼吗？KB Pay免费提供。使用KB Pay支付时获得额外优惠！',
    'common.view_more': '查看更多',
    
    // PICK 部分数据
    'pick.title_1': '圆润中安详的宁静',
    'pick.subtitle_1': '温泉',
    'pick.title_2': '圆润中安详的宁静',
    'pick.subtitle_2': '温泉',
    'pick.title_3': '圆润中安详的宁静',
    'pick.subtitle_3': '温泉',
    'pick.title_4': '圆润中安详的宁静',
    'pick.subtitle_4': '温泉',
    'pick.title_5': '圆润中安详的宁静',
    'pick.subtitle_5': '温泉',
    'pick.title_6': '圆润中安详的宁静',
    'pick.subtitle_6': '温泉',
    'pick.title_7': '圆润中安详的宁静',
    'pick.subtitle_7': '温泉',
    'pick.title_8': '圆润中安详的宁静',
    'pick.subtitle_8': '温泉',
    'pick.title_9': '圆润中安详的宁静',
    'pick.subtitle_9': '温泉',
    'pick.title_10': '圆润中安详的宁静',
    'pick.subtitle_10': '温泉',
    
    // 早鸟数据
    'earlybird.title_text': '早鸟特价',
    'earlybird.description': '限量特别折扣',
    'earlybird.cta': '立即预订',
    
    // 杂志数据
    'magazine.seowajeong': '西瓦亭',
    'magazine.seowajeong_desc': '传统与现代相遇的空间',
    'magazine.magazine_1': '杂志第1期',
    'magazine.magazine_2': '杂志第2期',
    'magazine.magazine_3': '杂志第3期',
    'magazine.magazine_4': '杂志第4期',
    'magazine.title_46': '从忙碌的日常生活中逃离享受的瞬间休息',
    'magazine.title_45': '与大海一起的特殊休息，海滩边的宁静',
    'magazine.title_44': '在森林中相遇的宁静，与自然一起的休息',
    'magazine.title_43': '属于自己的时间，比乌丹',
    'magazine.title_42': '在自然中寻找内心的平静',
    'magazine.title_41': '远离城市相遇的新体验',
    'magazine.title_40': '忘记时间享受的完美休息',
    'magazine.title_39': '发现小日常美丽的瞬间',
    'magazine.title_38': '与风一起的自由旅行',
    'magazine.title_37': '星光下的浪漫夜晚',
    'magazine.title_36': '山海相遇之处的疗愈',
    'magazine.title_35': '传统与现代和谐的空间',
    'magazine.title_34': '感受季节变化的特殊空间',
    'magazine.title_33': '寻找心灵余裕的疗愈时光',
    'magazine.title_32': '与自然一起的生态旅行',
    'magazine.title_31': '远离城市相遇的新体验',
    
    // 杂志页面
    'magazine.page_title': '杂志',
    
    // 住宿详情页面
    'accommodation.room_info.standard_capacity': '标准人数',
    'accommodation.room_info.checkin': '入住',
    'accommodation.room_info.checkout': '退房',
    'accommodation.room_info.area': '客房面积',
    'accommodation.room_info.spaces': '客房空间',
    'accommodation.room_info.bed_types': '床型',
    'accommodation.room_info.title': '客房信息',
    'accommodation.room_info.people': '人',
    'accommodation.room_info.max_people': '最多',
    'accommodation.amenities.title': '所有客房包含项目',
    'accommodation.amenities.view_all': '查看全部',
    'accommodation.amenities.hair_dryer': '吹风机',
    'accommodation.amenities.coffee_machine': '咖啡机',
    'accommodation.amenities.bathroom_amenities': '浴室用品',
    'accommodation.amenities.condiments': '调味料',
    'accommodation.amenities.outdoor_slippers': '户外拖鞋',
    'accommodation.amenities.microwave': '微波炉',
    'accommodation.amenities.hand_sanitizer': '手部消毒液',
    'accommodation.amenities.coffee_pot': '咖啡壶',
    'accommodation.amenities.refrigerator': '冰箱',
    'accommodation.amenities.air_conditioner': '空调',
    'accommodation.amenities.tv': '电视',
    'accommodation.amenities.induction': '电磁炉',
    'accommodation.amenities.cooking_utensils': '烹饪用具',
    'accommodation.amenities.tableware': '餐具',
    'accommodation.amenities.wine_opener': '开瓶器',
    'accommodation.amenities.wine_glass': '酒杯',
    'accommodation.amenities.towel': '毛巾',
    'accommodation.amenities.diffuser': '香薰机',
    'accommodation.info.title': '请确认注意事项',
    'accommodation.info.location': '位置指南',
    'accommodation.info.rules': '使用规则',
    'accommodation.info.refund': '退款政策',
    'accommodation.info.safety': '安全设施',
    'accommodation.info.pricing': '价格政策',
    'accommodation.info.address': '地址',
    'accommodation.info.contact': '联系方式',
    'accommodation.info.email': '邮箱',
    'accommodation.pricing.off_peak': '淡季',
    'accommodation.pricing.peak': '旺季',
    'accommodation.pricing.high_peak': '极旺季',
    'accommodation.pricing.weekday': '平日',
    'accommodation.pricing.weekend': '周末',
    'accommodation.pricing.category': '分类',
    'accommodation.pricing.note': '详细费用请在选择日期后确认。',
    'accommodation.pricing.basic_rate': '基本费用',
    'accommodation.pricing.peak_season_rate': '旺季费用',
    'common.currency_unit': '韩元',
    
    // Experience 部分
    'experience.yeoju.title': '骊州郡 : 东川',
    'experience.yeoju.subtitle': '美丽山景中的一夜清新',
    'experience.layr.title': 'LAYR',
    'experience.layr.subtitle': '层韩屋住宅',
    'experience.layr.description': '唤醒内心品味的空间',
    'experience.timezone.title': '独特时区',
    'experience.timezone.subtitle': '专属于我们的独特时光',
    'experience.ideal.title': '理想一天的体验',
    'experience.ideal.subtitle': '与Stayground一起体验',
    
    // 杂志详情页面
    'magazine.detail.hero.title': '杂志标题',
    'magazine.detail.hero.subtitle': '杂志副标题',
    'magazine.detail.description.title': '杂志描述',
    'magazine.detail.description.content': '杂志详细内容在这里。此部分描述了杂志的主要内容。',
    'magazine.detail.accommodation.title': '相关住宿',
    'magazine.detail.accommodation.subtitle': '查看与此杂志相关的住宿。',
    'magazine.detail.banner.title': '特别体验',
    'magazine.detail.banner.subtitle': '只有在Stayground才能体验的特殊时光',
    'magazine.detail.info.title': '详细信息',
    'magazine.detail.info.location': '位置',
    'magazine.detail.info.address': '地址',
    'magazine.detail.info.contact': '联系方式',
    'magazine.detail.info.email': '邮箱',
    'magazine.detail.info.website': '网站',
    'magazine.detail.navigation.previous': '上一个',
    'magazine.detail.navigation.next': '下一个',
    
    // 杂志详情页面表格标签
    'magazine.detail.table.stay_name': '住宿名称',
    'magazine.detail.table.type': '类型',
    'magazine.detail.table.capacity': '标准/最大容纳人数',
    'magazine.detail.table.rooms': '房间数',
    'magazine.detail.table.checkin_checkout': '入住/退房',
    'magazine.detail.table.address': '地址',
    'magazine.detail.table.amenities': '设施',
    'magazine.detail.button.book_now': '立即预订',
    'magazine.detail.button.inquiry': '咨询',
    'accommodation.inquiry': '咨询',
    
    // 住宿详情页面标签内容
    'accommodation.tab.room_spaces': '卧室(1), 浴室(2), 客厅(1), 厨房(1)',
    'accommodation.tab.checkin_checkout': '入住和退房',
    'accommodation.tab.checkin_time': '入住时间为下午3点，退房时间为上午11点。',
    'accommodation.tab.standard_capacity_detail': '标准人数为2人，最多6人（包括婴儿）。成人和儿童限制为5人。超过最大人数时绝对不允许入住。',
    'accommodation.tab.child_age': '儿童适用年龄为12岁以下。',
    'accommodation.tab.visitor_policy': '非住客访客在标准人数内加收额外费用后可使用（人数超限时不可使用）。',
    'accommodation.tab.pet_policy': '我们热爱宠物，但由于这是多人使用的共享空间，因此不允许携带宠物入住。',
    'accommodation.tab.cleaning_service': '连续住宿时不提供清洁服务。',
    
    // 住宿详情页面 Point 部分
    'accommodation.point1.title': '竹子传递的治愈之声',
    'accommodation.point1.description': '请专注于风中摇曳的竹林声音。木别位于被竹子环绕的自然中，让您在逗留期间享受竹子清新的绿色。作为木别围墙的竹子为卧室、客厅和浴室提供清新的光线，传递治愈能量。特别是茂密的竹林和尽头可见的三陟海，以及您在木别按摩浴缸中遇到的景色将成为难忘的治愈体验。',
    'accommodation.point2.title': '季节停留的庭院',
    'accommodation.point2.description': '私人庭院设有四季皆可享受的温泉池。浸泡在温水中，欣赏变化的自然风景，度过悠闲时光。夜晚，在星空下享受浪漫的游泳。位于庭院中央的温泉池是一个特殊的空间，让您全身感受季节的变化。它包含每个季节的所有美丽：春天新芽的声音，夏天蝉鸣，秋天落叶的声音，以及冬天宁静的寂静。',
    'accommodation.point3.title': '极简设计的舒适',
    'accommodation.point3.description': '客房内部采用极简设计装饰，配备所有必要的便利设施，提供舒适的休息。通过落地窗将外部风景引入室内，让您可以从任何地方欣赏自然。利用裸露混凝土、玻璃和竹子的设计将自然元素带入建筑，营造现代而温暖的氛围。您可以在每个空间感受到与自然的和谐，享受真正的休息和治愈时光。',
    
    // 首页杂志部分数据
    'magazine.home.title_46': '从忙碌的日常生活中逃离享受的瞬间休息',
    'magazine.home.title_45': '放慢脚步相遇的宁静，西瓦亭',
    'magazine.home.title_44': '充满大海、竹林和星星共鸣的空间',
    'magazine.home.title_43': '属于自己的时间，比乌丹',
    
    // 住宿页面搜索栏翻译
    'stay.search.destination': '目的地',
    'stay.search.destination_placeholder': '搜索目的地/住宿',
    'stay.search.checkin': '入住',
    'stay.search.checkin_placeholder': '搜索入住日期',
    'stay.search.checkout': '退房',
    'stay.search.checkout_placeholder': '搜索退房日期',
    'stay.search.people': '人数',
    'stay.search.people_placeholder': '选择人数',
    'stay.search.apply': '应用',
    'stay.search.adult': '成人',
    'stay.search.child': '儿童',
    'stay.search.infant': '婴儿',
    'stay.search.people_count': '人',
    
    // 住宿页面图标网格翻译
    'stay.icons.all_stays': '所有住宿',
    'stay.icons.ending_soon': '即将结束',
    'stay.icons.private_stay': '独立住宿',
    'stay.icons.camping': '露营&豪华露营',
    'stay.icons.pet_friendly': '宠物友好',
    'stay.icons.pool': '游泳池',
    'stay.icons.jacuzzi': '按摩浴缸',
    'stay.icons.hanok': '韩屋',
    'stay.icons.ocean_view': '海景',
    'stay.icons.forest_view': '森林景观',
    'stay.icons.city_view': '城市景观',
    'stay.icons.harbor_view': '港口景观',
    'stay.icons.sauna': '桑拿',
    
    // 住宿页面过滤器翻译
    'stay.filter.recommended': '推荐',
    'stay.filter.latest': '最新',
    'stay.filter.popular': '热门',
    'stay.filter.price_high': '价格从高到低',
    'stay.filter.price_low': '价格从低到高',
    'stay.filter.filter': '过滤器',
    'stay.filter.reset': '重置',
    'stay.filter.apply': '应用',
    
    // 住宿页面位置翻译
    'stay.location.all': '全部',
    'stay.location.seoul': '首尔',
    'stay.location.busan': '釜山',
    'stay.location.daegu': '大邱',
    'stay.location.incheon': '仁川',
    'stay.location.daejeon': '大田',
    'stay.location.gwangju': '光州',
    'stay.location.ulsan': '蔚山',
    'stay.location.gyeonggi': '京畿道',
    'stay.location.gangwon': '江原道',
    'stay.location.chungnam': '忠清南道',
    'stay.location.chungbuk': '忠清北道',
    'stay.location.jeonnam': '全罗南道',
    'stay.location.jeonbuk': '全罗北道',
    'stay.location.gyeongnam': '庆尚南道',
    'stay.location.gyeongbuk': '庆尚北道',
    'stay.location.jeju': '济州道',
    
    // 住宿页面便利设施翻译
    'stay.amenities.four_season_pool': '四季温水泳池',
    'stay.amenities.bbq': 'BBQ',
    'stay.amenities.outdoor_bath': '露天浴池',
    'stay.amenities.fire_pit': '篝火',
    'stay.amenities.walking_trail': '散步道',
    'stay.amenities.terrace': '露台',
    'stay.amenities.breakfast': '早餐',
    'stay.amenities.smart_home': '智能家居',
    'stay.amenities.fitness': '健身(健身房)',
    'stay.amenities.yoga': '瑜伽',
    'stay.amenities.karaoke': '卡拉OK',
  }
}

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('ko')

  // 초기 언어 설정 (localStorage에서 복원)
  useEffect(() => {
    if (typeof window !== 'undefined') {
      const savedLanguage = localStorage.getItem('selectedLanguage') as Language
      if (savedLanguage && ['ko', 'en', 'zh'].includes(savedLanguage)) {
        setLanguage(savedLanguage)
      }
    }
  }, [])

  const t = (key: string): string => {
    return (translations[language] as any)[key] || key
  }

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    // localStorage에 언어 설정 저장
    if (typeof window !== 'undefined') {
      localStorage.setItem('selectedLanguage', lang)
      // 현재 페이지가 홈페이지가 아니면 홈페이지로 이동
      if (window.location.pathname !== '/') {
        window.location.href = '/'
      }
    }
  }

  return (
    <LanguageContext.Provider value={{ 
      language, 
      setLanguage: handleSetLanguage, 
      t 
    }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
